### ISSUE TITLE
Missing help text for search field

### ISSUE THREAD

**Issue by Rastopapola** [nursix/eden#84] opened 2020-04-27 12:10 UTC
# Status quo 
The search field in **Freiwillige** is not self-explanatory and therefore any input results in an ampty table set.

# Improvement
1. Add a help text below or next to the input field, which states what exactly the search field will search for.
1. If names are used for a search, we should extend the search to search in **Berufsgruppe** and **Wohnort**  as well, since the names are not visible for some groups which do not have permissions to see them. They would always end up in an empty table, making the search field pointless.

**Comment by nursix** [comment] 2020-04-27 12:24
The search field searches ID and names.

Occupation type and place of residence can be searched using the specific search widgets for those (see "More Options") - not the text filter.

Hidden names (***) cannot be found - for obvious reasons. All other names can be found - as well as all IDs, which would be the primary means of off-system comms (e.g. notification email).

A help text can be added to explain what the search field is for, but an extension to other search fields is not useful as they are better (and far more efficiently) searched using the corresponding filters.

**Comment by Rastopapola** [comment] 2020-04-27 13:03
Sounds plausible.

>A help text can be added to explain what the search field is for, but an extension to other search fields is not useful as they are better (and far more efficiently) searched using the corresponding filters.

Alright, then. The help text should clarify that (obviously) anonymized names can not be searched for.

**Comment by nursix** [comment] 2020-04-27 13:13
Interesting that you say it is obvious that you cannot search for anonymous names - and yet want it clarified in the help text...I wonder why a user would even attempt to search by a name they cannot possibly know - or expect to find an anonymized record by name?

I think the help text would then say that you can "search by ID - and by name for records which have names", but doesn't that sound a little as if we take the users for fools?

**Comment by nursix** [comment] 2020-04-27 13:15
Oh - or wait: they may know the person once the volunteer has been deployed to their site, and then attempt to find their record. Right...so yes, we should indeed say it like that (although I still think it's obvious :D)

Will do.

**Comment by Rastopapola** [comment] 2020-04-27 13:25
>Interesting that you say it is obvious that you cannot search for anonymous names - and yet want it clarified in the help text...

Hehe, yes, sounds chaotic but you got my point! It could be that the volunteer has already been contacted on some other way and the user wants to find this person using the search field in the app. 

Using the search field for names is the expected behaviour, absoluely. But I mostly think of easily-panicking users, who now have to coordinate their workflow using this system. They might get a heart attack, entering an input and retrieving an empty table: "Did I delete it? Oh my god, I deleted it! I will lose my job!"

We are not expecting to have "tech-experts" as users, so let's take them by the hand as much as possible :D

**Comment by nursix** [comment] 2020-04-27 13:32
Yeah - as long as it doesn't make them feel patronized...

Fixed by https://github.com/nursix/eden/commit/29144313ea65d5de20f10de68b733885979e7177

**Closed by nursix** 2020-04-27 13:32 UTC

**Comment by Rastopapola** [comment] 2020-04-27 13:37
>Yeah - as long as it doesn't make them feel patronized...

I really understand your concerns. From my experience in this field (so far), most are thankful for as-self-explanatory-as-possible systems and always know at least one or two colleagues who are really in need of these little helping things.

Thanks for the quick fix!

**Comment by nursix** [comment] 2020-04-27 13:38
P.S. You may have noticed that they cannot delete volunteers ;) so no need to panic. And even if they could, they couldn't do so accidentally because delete asks for explicit confirmation. And even if they had confirmed it under duress, there's still a mighty sysadmin team who can restore it. Nobody will die. We pamper them quite well.

**Comment by Rastopapola** [comment] 2020-04-27 13:39
>P.S. You may have noticed that they cannot delete volunteers ;) so no need to panic. And even if they could, they couldn't do so accidentally because delete asks for explicit confirmation. And even if they had confirmed it under duress, there's still a mighty sysadmin team who can restore it. Nobody will die. We pamper them quite well.

;D

So let them feel the safety we provide them :1st_place_medal:

**Comment by nursix** [comment] 2020-04-27 13:42
Should I update the demo? Looks quite busy there right now, so better leave it for later?

**Comment by Rastopapola** [comment] 2020-04-27 13:46
Yes, they have been in a demo session, until a few minutes ago. Sounds like a few ideas and requests have been stated. There will be some news from Armin and then I'm going to open the related issues, in which we can discuss then.

The staging pull might be all in one after everything has been implemented/fixed.

**Comment by nursix** [comment] 2020-04-27 13:51
Okay, quiet there now - so I updated the demo server now (only takes a second, but still disruptive when in the middle of a session).

GitHub issues are great, of course, but perhaps better with a chat in this case as otherwise I need to track them in different places.

**Comment by Rastopapola** [comment] 2020-04-27 13:53
>(only takes a second, but still disruptive when in the middle of a session).

Absolutely relatable.

>GitHub issues are great, of course, but perhaps better with a chat in this case as otherwise I need to track them in different places.

Just tell me where you want to be contacted, we find a solution.
